In [2]:
import numpy as np

X = np.array([[3, -1], [4, 2], [2, 1]])
Y = np.array([[2], [1], [1]])

print(X)
print(Y)

[[ 3 -1]
 [ 4  2]
 [ 2  1]]
[[2]
 [1]
 [1]]


In [3]:
W = np.linalg.inv(X.T @ X) @ X.T @ Y
print(W)

[[ 0.52]
 [-0.44]]


In [6]:
sig_2 = 5
tau_2 = 0.2
W = np.linalg.inv(X.T @ X + sig_2 / tau_2 * np.eye(2)) @ X.T @ Y
print(W)

[[ 0.22461538]
 [-0.01846154]]
